### ISSUE TITLE
Error in speedup

### ISSUE THREAD

**Issue by rodyo** [rodyo/FEX-SkippingStone#1]
As reported by [Suraj Parasuram](https://www.mathworks.com/matlabcentral/fileexchange/29272-skipping-stone-an-interplanetary-space-mission-design-tool?s_tid=mlc_fex_email_activity#feedback-b8ecaa8d-7764-49de-9028-c8a75f8f0843):

When I run main.m I get this error :
Cannot CD to
C:\Users\Owner\Downloads\rodyo-FEX-SkippingStone-0825d3f\rodyo-FEX-SkippingStone-0825d3f\orbital_mechanics\propagate_orbit
(Name is nonexistent or not a directory).

Error in speedup (line 95 )
cd(fullfile(rootdir,'orbital_mechanics','propagate_orbit'));

**Comment by markbentzjr** [comment]
Hi, I'm getting the same error and when running main.m, I get this error

Unrecognized function or variable 'tsjiolkovsky'.

Error in callbacks/max_total_DV_check (line 989)
        max_DV_possible = tsjiolkovsky([], current_Isp, current_M0, current_Me);

Error in callbacks (line 91)
        feval(funfcn, varargin{:});

Error in build_main_window (line 2617)
    callbacks('max_total_DV_check',...

Error in main (line 120)
    build_main_window(environment,...

**Comment by rodyo** [comment]
Just to check - how have you checked out this repository? It uses [submodules](https://git-scm.com/book/en/v2/Git-Tools-Submodules) (`tsjiolkovsky` and `propagate_orbit` being 2 of them), so you should use 

`git clone --recurse-submodules https://github.com/rodyo/FEX-SkippingStone.git`

(note the `--recurse-submodules` option).

**Comment by markbentzjr** [comment]
Yes, I realized I was missing modules and downloaded them then it started working!

**Comment by rodyo** [comment]
Great to hear 😊 I'll close this issue then. 

As an aside, FYI: this is a tool I've written for my MSc thesis, 2009–2010. It hasn't received significant updates since then, and it was my first sizable piece of software...I'm not terribly happy with the code quality and extensibility, but the results have (for the most part) been validated.
